import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {Toaster} from "react-hot-toast";
import {AntdRegistry} from '@ant-design/nextjs-registry';

import {AdaptiveBackground} from '@/components/background';

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    {/*Add Ant Registry to avoid first loading page flicker*/}
    <AntdRegistry>
      <AdaptiveBackground>
        <Toaster/>
        {children}
      </AdaptiveBackground>
    </AntdRegistry>
    </body>
    </html>
  );
}
